### ISSUE TITLE
FAQ: Indexes

### ISSUE THREAD

**Issue by tjworks** [tjworks/docs#410]
PO File: https://github.com/tjworks/docs/blob/master/locale/zh/LC_MESSAGES/faq/indexes.po
Chinese Page: http://staging.mongoing.com/manual-zh/faq/indexes.html
English Page: http://docs.mongodb.org/manual/faq/indexes

**Comment by arthurhoo** [comment]
我发现中文页没有改变，这个是怎么回事？还需要别的步骤吗？

**Comment by arthurhoo** [comment]
@tjworks
