### ISSUE TITLE
Default Write Concern Change

### ISSUE THREAD

**Issue by tjworks** [tjworks/docs#430]
PO File: https://github.com/tjworks/docs/blob/master/locale/zh/LC_MESSAGES/release-notes/drivers-write-concern.po
Chinese Page: http://staging.mongoing.com/manual-zh/release-notes/drivers-write-concern.html
English Page: http://docs.mongodb.org/manual/release-notes/drivers-write-concern

**Comment by Yingminzhou** [comment]
test comments
